DROP VIEW IF EXISTS vw_ColourList
GO 

CREATE VIEW vw_ColourList
AS 

SELECT * FROM 
(VALUES 
	(1, 'light blue')
	, (2, 'dark blue')
	, (3, 'light green')
	, (4, 'red')
	, (5, 'BLACK')
	, (6, 'BLACK')
	, (7, 'BLACK')
	, (8, 'BLACK')
	, (9, 'BLACK')
	, (10, 'BLACK')
	, (11, 'BLACK')
	, (12, 'BLACK')
	, (13, 'BLACK')
	, (14, 'BLACK')
	, (15, 'BLACK')
	, (16, 'BLACK')
	, (17, 'BLACK')
	, (18, 'BLACK')
	, (19, 'BLACK')
	, (20, 'BLACK')
	, (21, 'BLACK')
	, (22, 'BLACK')
	, (23, 'BLACK')
	, (24, 'BLACK')
	, (25, 'BLACK')
	, (26, 'BLACK')
	, (27, 'BLACK')
	, (28, 'BLACK')
	, (29, 'BLACK')
	, (30, 'BLACK')
	, (31, 'BLACK')
	, (32, 'BLACK')
	, (33, 'BLACK')
	, (34, 'BLACK')
	, (35, 'BLACK')
	, (36, 'BLACK')
	, (37, 'BLACK')
	, (38, 'BLACK')
	, (39, 'BLACK')
	, (40, 'BLACK')
	, (41, 'BLACK')
	, (42, 'BLACK')
	, (43, 'BLACK')
	, (44, 'BLACK')
	, (45, 'BLACK')
	, (46, 'BLACK')
	, (47, 'BLACK')
	, (48, 'BLACK')
	, (49, 'BLACK')
	, (50, 'BLACK')
	, (51, 'BLACK')
	, (52, 'BLACK')
	, (53, 'BLACK')
	, (54, 'BLACK')
	, (55, 'BLACK')
	, (56, 'BLACK')
	, (57, 'BLACK')
	, (58, 'BLACK')
	, (59, 'BLACK')
	, (60, 'BLACK')
	, (61, 'BLACK')
	, (62, 'BLACK')
	, (63, 'BLACK')
	, (64, 'BLACK')
) x(ID, Colour)